In [539]:
##Importing all required libraries
import numpy as np
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
#from xgboost import XGBRegressor
#from sklearn.tree import DecisionTreeRegressor
#from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge
#from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [350]:
## importing Dataset from local Machine

appl_Data= pd.read_csv(r"C:\Users\Blessing_Iyobosa\Downloads\energydata_complete.csv")
appl_Data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [351]:
appl_Data.describe()

## no missing values from count observation across all features

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [352]:
appl_Data.drop(columns=['date','lights'],axis=1,inplace=True)
appl_Data.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [540]:
temp_data = appl_Data[['T2','T6']]

#(Take note of the initials of the defined variables below)

x_train, x_test,Y_train, Y_test = train_test_split(temp_data.drop(columns=['T6']),temp_data['T6'],test_size = 0.3,random_state = 42)
LinearRegression().fit(x_train,Y_train)
temp_predict = LinearRegression().fit(x_train,Y_train).predict(x_test)
temp_r2_score = r2_score(Y_test,temp_predict)
print(temp_r2_score)

print('R2 Score:{:.2f}'.format(temp_r2_score))

0.6427789637197382
R2 Score:0.64

In [371]:
## -already imported---from sklearn.preprocessing import MinMaxScaler

sca_appl_Data = MinMaxScaler().fit_transform(appl_Data)
sca_appl_Data = pd.DataFrame(sca_appl_Data ,columns = [appl_Data .columns])
sca_appl_Data 

X = sca_appl_Data.drop(columns=['Appliances'])
#X
y = sca_appl_Data[['Appliances']]
#Y


###Test and Train data
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size =0.3,random_state=42)
#X_train, X_test, y_train, y_test

<ipython-input-371-1a82e9c400c2>:7: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  X = sca_appl_Data.drop(columns=['Appliances'])

In [445]:
appl_predict = LinearRegression().fit(X_train,y_train).predict(X_test)

mae = mean_absolute_error(y_test,appl_predict)
print('Mean Squared Error: {:.2f}'.format(mae))


rss = np.sum(np.square(y_test-appl_predict))
print('Residual Sum of Squares:',float(rss))

mse = np.sqrt(mean_squared_error(y_test,appl_predict))
print('Root mean squared error:{:.3f}'.format(mse))

r2_score = r2_score(y_test,appl_predict)
print('Coefficient of Determination:{:.2f}'.format(r2_score))

Mean Squared Error: 0.05
Residual Sum of Squares: 45.34762967266377
Root mean squared error:0.088
Coefficient of Determination:0.15

In [529]:
from sklearn.linear_model import Lasso

l_regr = LinearRegression()
la_regr = Lasso(alpha = 0.001)

def feature_importance(model,feat):
    weight = model.fit(X_train,y_train).coef_
    weight= weight.reshape(26,1)
    feature_df = pd.DataFrame(weight,feat.columns).reset_index().sort_values(by=0)
    max = feature_df[feature_df[0] == feature_df[0].max()]
    min = feature_df[feature_df[0] == feature_df[0].min()]
    return(max,min,feature_df)
    
feature_importance(l_regr,X_train)
#feature_importance(la_regr,X_train)

(  level_0         0
 1    RH_1  0.553547,
   level_0         0
 3    RH_2 -0.456698,
         level_0         0
 3          RH_2 -0.456698
 18        T_out -0.321860
 2            T2 -0.236178
 16           T9 -0.189941
 15         RH_8 -0.157595
 20       RH_out -0.077671
 13         RH_7 -0.044614
 17         RH_9 -0.039800
 8            T5 -0.015657
 0            T1 -0.003281
 24          rv1  0.000770
 25          rv2  0.000770
 19  Press_mm_hg  0.006839
 12           T7  0.010319
 22   Visibility  0.012307
 9          RH_5  0.016006
 7          RH_4  0.026386
 6            T4  0.028981
 21    Windspeed  0.029183
 11         RH_6  0.038049
 5          RH_3  0.096048
 14           T8  0.101995
 23    Tdewpoint  0.117758
 10           T6  0.236425
 4            T3  0.290627
 1          RH_1  0.553547)

In [530]:
from sklearn.linear_model import Ridge

ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(X_train, y_train)
ridge_pred = ridge_reg.predict(X_test)

ridge_reg.fit(X_train, y_train).score(X_train,y_train)
ridge_reg.fit(X_train, y_train).score(X_test,y_test)


mse_ridge = np.sqrt(mean_squared_error(y_test,ridge_pred))
print('Root mean squared error:{:.3f}'.format(mse_ridge))  ### Answer is Same as the previous RSME

Root mean squared error:0.088

In [534]:
from sklearn.linear_model import Lasso

la_regr = Lasso(alpha = 0.001)

def feature_importance(model,feat):
    weight = model.fit(X_train,y_train).coef_
    weight= weight.reshape(26,1)
    feature_df = pd.DataFrame(weight,feat.columns).reset_index().sort_values(by=0)
    max = feature_df[feature_df[0] == feature_df[0].max()]
    min = feature_df[feature_df[0] == feature_df[0].min()]
    return(max,min,feature_df[feature_df != 0])
    
#feature_importance(l_regr,X_train)
feature_importance(la_regr,X_train)

## Only 4 Features are Non-Zero (RH_Out,RH_8,Windspeed,RH_1)

(  level_0        0
 1    RH_1  0.01788,
    level_0         0
 20  RH_out -0.049557,
         level_0         0
 20       RH_out -0.049557
 15         RH_8 -0.000110
 0            T1       NaN
 23    Tdewpoint       NaN
 22   Visibility       NaN
 19  Press_mm_hg       NaN
 18        T_out       NaN
 17         RH_9       NaN
 16           T9       NaN
 14           T8       NaN
 13         RH_7       NaN
 24          rv1       NaN
 12           T7       NaN
 10           T6       NaN
 9          RH_5       NaN
 8            T5       NaN
 7          RH_4       NaN
 6            T4       NaN
 5          RH_3       NaN
 4            T3       NaN
 3          RH_2       NaN
 2            T2       NaN
 11         RH_6       NaN
 25          rv2       NaN
 21    Windspeed  0.002912
 1          RH_1  0.017880)

In [537]:
lasso_reg= la_regr.fit(X_train,y_train)

lasso_predict = lasso_reg.predict(X_test)

rmse_lasso = np.sqrt(mean_squared_error(y_test,lasso_predict))
print('Root mean squared error:{:.3f}'.format(rmse_lasso))

Root mean squared error:0.094